micronaut:
  application:
    name: demo

  http:
    services:
      users-api:
        connect-timeout: 30s
        read-timeout: 30s
        event-loop-group: users-api

  netty:
    event-loops:
      default:
        num-threads: 1
      users-api:
        executor: io
        num-threads: 1
      consul:
        executor: io
        num-threads: 1
netty:
  default:
    allocator:
      max-order: 3

users:
  api:
    # application-test.yml
    # USERS_API_KEY
    # -Dusers.api.key=...
    key: 4d206816-6f48-4bc1-a437-bb5ddd6dc95f


consul:
  client:
    registration:
      enabled: true
    default-zone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
    event-loop-group: consul

aws:
  sqs:
    endpoint: http://localhost:4566