micronaut:
  server:
    port: 35123

  application:
    name: users-api

  security:
    enabled: true
    intercept-url-map:
      - pattern: /health
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /swagger/**
        access:
          - isAnonymous()

    api-keys:
      4d206816-6f48-4bc1-a437-bb5ddd6dc95f: Mark Spencer

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

swagger-ui:
  enabled: true

datasources:
  default:
    url: jdbc:mysql://localhost:53307/demo?useUnicode=yes&characterEncoding=UTF-8
    username: demo
    password: demo
    driverClassName: org.mariadb.jdbc.Driver
    schema-generate: CREATE
    dialect: MYSQL

netty:
  default:
    allocator:
      max-order: 3


consul:
  client:
    registration:
      enabled: true
    default-zone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
